---
title: "Towards a Vision for Team Science at Tilburg University"
format: pdf
---

<!-- Insert here -->
**Defining Team Science** (@sec-definition)

1. Team Science can be defined as collaboration with a larger number of partners than is standard in a particular domain of study, addressing a goal that transcends what could be achieved by a single scholar, capitalizing on team members' strengths, with attention to their diverse perspectives, and members from multiple branches of the organization (including scientific and support staff), and/or other stakeholders.

**Benefits and Challenges of Team Science** (@sec-benefitschallenges)

2. Team science benefits both individual team members, the organization, and society at large, and allows scholars to provide complex solutions to large-scale public challenges. It promotes collaboration, cohesion, and knowledge exchange within organizations, increases impact, and may benefit research quality.

3. Any science team should be aware of, and reflect on how they relate to, the seven challenges of team science: diversity, knowledge integration, team size, goals, permeable boundaries, geographic dispersion, and task interdependence.


**Local Perspective** (@sec-goodpractices)

4. At present, only 3% of academic output involves authors from multiple Schools. If connecting the schools is considered important, then promoting team science initiatives that connect the schools is low-hanging fruit.

**Open Science: Lessons Learned** (@sec-openscience)

5. The open science transition serves as a template for the transition towards more team science, and the Open Science Community Tilburg is a natural ally in achieving this transition.

6. Open science practices facilitate team science, reduce onboarding efforts and improve scalability, increase the reusability of materials, data, and code, increase scientific rigor, and offer a greater potential payoff to team members.

**Team Effectiveness** (@sec-effectiveness)

7. Team effectiveness is enhanced by thoughtful team composition, team professional development, building a shared understanding of goals, task requirements, and team member competencies, and inspiring person-focused team leadership.

**Communication and Team Success** (@sec-communication)

8. Team members should be able to disagree constructively in a safe, supportive context. When possible, preemptive conflict management strategies should be used; anticipating disagreements and establishing terms for their constructive resolution. When conflict does occur, reactive conflict management should focus on empathy, problem-solving, and compromise. Professional development opportunities should be in place to educate staff in the use of such communication techniques.

**Procedural Fairness** (@sec-proceduralfairness)

9. Ensure trust within team contexts to facilitate effective collaboration, for example, through procedural fairness and transparency within science teams and the broader organization, and through face-to-face interaction between team members.

10. Consider adopting or developing a code of conduct that clearly outlines expectations for how the team members will ensure social safety, resolve disagreements, credit contributions, ensure ethical and responsible research practices, and provides recourse in case anything goes wrong.

**Team Composition** (@sec-composition)

11. When composing a team, it is crucial to weigh the benefits of *task relevant diversity* against the downsides of overcoming disciplinary, institutional, or demographic differences.

12. Starting at the undergraduate level, train young academics in interdisciplinarity and collaborative skills.

**Permeable Team Boundaries** (@sec-boundaries)

13. It is important to maintain a stable core membership in teams with permeable boundaries to foster team cohesion and sustained performance.

14. For all temporary team members, in particular early career academics and those on temporary contracts, the balance between investments (in terms of time and effort) and rewards should be explicit and fair.

**Support staff** (@sec-supportstaff)

15. Recognition and rewards should affect support staff as well, ensuring that support staff are incentivized to contribute to team science.

16. Increase social and professional ties between all university staff (scientific and support) by welcoming all staff at the same training- and social events.

17. Decentralize support staff and locate them (physically) closer to the researchers, at least temporarily - for example, by having consultation hours in different buildings - thus enabling easier collaboration (see @sec-physicalenvironment).

18. Organizational policies should strive to create a climate conducive to team science by incentivizing collaboration,
making hierarchies flexible, supporting autonomy, embracing open science,
recognizing and rewarding team science, team spirit,
and inspiring team-oriented leadership.

19. Redefine "excellence" to no longer exclusively refer to individual performance, but also provide a concrete outline of what constitutes excellence in a team context.

**Flexible Hierarchies** (@sec-hierarchy)

20. In order for team science to flourish, TiU must balance hierarchy and specialization on the one hand with collaboration and integration on the other. Hierarchy must be flexible: it must be possible to check, question, and even challenge authority.

**Top down and Bottom Up** (@sec-topdownbottomup)

21. To enact a desired culture change towards more team science, a combination of a top-down (through policy, funding opportunities, and recognition and rewards) and bottom-up (through informal networks like the Open Science Community, and social, academic, and networking events) approaches is necessary.


**Funding Team Science** (@sec-funding)

22. Using public funds (eerste geldstroom) to fund (interdisciplinary) team science initiatives can affect more colleagues' careers in a more impactful way, while promoting cohesion within the organization. To do this fairly and transparently, the target audience should be included in the development of funding calls.

23. Applications for team science funding instruments should include a collaboration plan as part of the evaluation criteria.

24. Monitor and evaluate existing internal funding programs aimed at stimulating collaboration across the schools.

25. Monitor and evaluate existing internal funding programs aimed at stimulating collaboration across the schools.

26. Create incubator grants, seed funding, and other flexible funding schemes to incentivize team science at all levels of seniority.

**Funding Pitfalls** (@sec-fundingpitfalls)

27. When reviewing funding applications, do not take prior funding success into account to avoid the "Matthew effect". Focus on merit and feasibility.

28. When reviewing team science funding applications, ensure diverse panels of reviewers, and prime them to value innovation and interdisciplinarity.

**Technology and Infrastructure** (@sec-it)

29. Technology and infrastructure should provide support and tools for collaboration, without creating a rigid mold that science teams are expected to conform to.

30. As much as possible, use open source software for all task-critical activities to ensure that all team members can participate and contribute, regardless of institutional licenses for specific software and services.

31. Use
reproducible workflows and make all scholarly output FAIRly shareable in order to ensure effortless (distributed) collaboration among team members,
make scholarly output FAIRly shareable,
increase the reusability of scholarly output,
and safeguard against human error that might otherwise go undetected.

**Team Science and the Physical Environment** (@sec-physicalenvironment)

32. Establish physical spaces that incentivize scholars from different disciplines and schools to mix. For example, Oxford-style “common rooms" with free (good) coffee and cookies, where researchers from different disciplines can meet, exchange ideas, and work on projects together.

33. Create a university-wide calendar of colloquia, symposia, brown bag lunches, et cetera, so (academic and support) staff is incentivized to attend events from other departments. Consider incentivizing use of this shared calendar by making funds for simple catering available to participating events.

**Training for Team Science** (@sec-training)

34. Teach effective collaboration skills at all levels by creating a FAIR resource page for teachers on how to effectively incorporate team work in education.

35. Offer training and workshops on team science principles, collaboration skills, and project management. These programs can help staff develop the skills needed for successful interdisciplinary work.

36. TiU should offer evidence-based, cross-disciplinary team trainings for team science. This includes training individuals in skills required for effective teamwork, and training teams as a whole to build shared goals and representations.

37. TiU should develop simple guidelines, readily available to all staff, to help teams engage in reflexivity and professionalization.

**Leadership Training for Team Science** (@sec-leadershiptraining)

38. When training connected leadership skills, emphasize transformative leadership for team science, that empowers team members to bring out their best. Recognize that, in team contexts, shared leadership can be more effective than hierarchical leadership (@sec-hierarchy).

**Recognition and Rewards in Relation to Team Science** (@sec-randr)

39. Task a working group with developing and evaluating general principles and specific criteria for recognizing team science contributions, and transparently incorporate these criteria in vacancies, PT&D conversations, and tenure and promotion committees.

40. Encourage engagement of PhD candidates in team science projects. Create more opportunities for the involvement of PhD candidates in ongoing teams with permeable boundaries, encourage supervisors to stimulate PhD candidates to become involved in team science efforts, and ask graduate schools to encourage supervisors to do so.


41. Establish grants for collaborative PhD projects on thematic topics that require interdisciplinary and inter-faculty team science.

42. Create a profile for professorships that span departments or schools, to promote interdisciplinary research and teaching.

**What to Recognize and Reward?** (@sec-whattoreward)

43. Preparations are in the works to adopt the MERIT system as official guiding principle for PT&D, hiring, and promotions at TiU. Evaluate the success of this transition. Alongside the MERIT system,
allow employees to specialize along its key dimensions, and ask organizational bodies to create vacancies that require a specific profile.

**(Inter)national Developments** (@sec-internationalrandr)

44. Along with other Dutch universities, TiU has committed to develop an action plan based on the international guidelines in [CoARA](https://coara.eu/agreement/the-commitments/) and [DORA](https://sfdora.org/read/) to revise our approach to research evaluation in 2024.

45. To ensure that TiU staff remain competitive in (inter)national funding calls from DORA signatories (e.g., NWO, ERC), TiU should abandon the irresponsible use of metrics and the use of aggregate-level metrics which are not valid for assessing individual researchers' performance. Instead, TiU should require internal performance reviews to focus on quality and individual-level quantitative metrics, and optionally, a narrative resumé.

46. In performance review and hiring decisions, TiU should consider the impact of all research output, including datasets, instruments, software, and valorization, alongside publications, and adopt a broad range of impact measures, including qualitative indicators of research impact like policy influence.

**Crediting Author Contributions** (@sec-credit)

47. Fairly and transparently credit each team member's contribution in the creation of research output.

48. Explicitly state what convention was followed to credit contributions, along with a reference.

49. The CRediT contributor taxonomy is a sensible default system for crediting contributions. Translating it into Dutch is low-hanging fruit and will make the taxonomy more accessible to people outside academia (e.g. policy makers, public partners and citizens/taxpayers).

**Monitoring and Evaluating Team Science** (@sec-monitoring)

50. All science teams should plan for formative assessments at given milestones during the project lifecycle. TiU should require summative evaluation of team science projects funded by the University (eerste geldstroom).
<!-- To here -->
