---
title: "There's No I in Science"
format: revealjs
---


## Defining Team Science {.smaller}

> **Team Science**: research conducted interdependently by multiple individuals (Cooke, Hilton, & Council, 2015).

- Often, but not always, interdisciplinary
- Essential for solving multifaceted challenges like climate change, inequality, and health (psychosocial determinants) (Ledford, 2015; Korthals Altes, 2014)

> **Revised definition:**
>   - Collaboration with more partners than typical in a field
>  - Focus on goals beyond individual achievement
>  - Emphasizes diverse perspectives and stakeholder inclusion  
  
**Who has participated in *team science*?**

## Team Science Benefits {.smaller}

- **Impact**: Address major social, economic, and ecological challenges (Allen & Mehler, 2019; Cannon, 2020).
- **Strength-based collaboration**: specialization allows team members to contribute what comes easier to them (writing, data collection, public engagement)
- **Pool Resources**: increased statistical power (Klein et al., 2014), replication, costly data (fMRI), compute
- **Creativity, Insight, and Diverse Perspectives** (Cannon, 2020).
- **Career advantages**: Team publications have a citation advantage, particularly valuable for early career scholars (Wuchty, Jones, & Uzzi, 2007).
- **Well-being**: community and empowerment researchers (Mydin et al., 2021).
- **Mentorship**: Teams facilitate mentoring and skills transfer
- **Research **: Collaboration enhances the reproducibility and trustworthiness of research.

## Challenges of Team Science {.smaller}

- **Social Loafing** (Simms & Nichols, 2014)
- **Self Bias**: Everyone feels like they contributed most (Johnston & Miles, 2010)
- **Start-up costs**: building relationships, establishing modus operandi
- **Hard to get funded** (Bromham et al., 2016)
- **Coordination** (Forscher et al., 2023)
- **Diversity challenges**: Diverse perspectives promote innovation but raise communication barriers (Nielsen et al., 2017)
- **Knowledge integration**: synthesis is not automatic; requires work (Conn et al., 2019).
    + TMSR cooperation
- **Team size paradox**: Smaller teams coordinate better, but larger teams outperform in publications and impact (Cummings, 2018)
- **Misaligned goals** between team members and external partners (Patel et al., 2021).
- **Physical distance**: better since COVID, but... (Earley & Mosakowski, 2000)
    + RSM Strategy Committee (AUS, USA, EUR)
- **Task interdependence**: Success depends on others (Conn et al., 2019)

## Team Science and Open Science {.smaller}

**Open science *greases the wheels* of team science.**

> UNESCO: open science [comprises] practices aiming to make scientific knowledge openly available, accessible and reusable for everyone, to increase scientific collaborations and sharing of information for the benefits of science and society, and to open the processes of scientific knowledge creation, evaluation and communication to societal actors beyond the traditional scientific community.

FAIR: Findable, Accessible, Interoperable, Reusable

* First with your (future) self
* Then with colleague next door, supervisor, co-author
* Then with larger teams
* Then with the world!
* Reducing onboarding time, improving scalability

## Specific Open Science Practices {.smaller}

* Open/reproducible code increases reusability of team members' contributions (Van Lissa et al., 2021)
    * Reduces onboarding and improves scalability (Baumgartner et al. 2023)
    * Allows team members to replicate and verify each other's work, enhancing rigor
* Public engagement-dimension of open science constitutes a form of team science
    * Add perspectives, increase relevance for stakeholders (Tebes and Thai 2018)
* Preregistration outlines scope of work-to-be-done and prevents disagreements about analytic decisions after seenig the results (Peikert, Van Lissa, and Brandmaier 2021)
* Registered Reports offer “guaranteed payoff” for team efforts (Baumgartner et al. 2023)
* Open access publication makes output accessible to wider audience
    * Not all stakeholders may have access to certain outlets
    * Ensure that all who have contributed retain access


## Team Effectiveness

> **Input-Process-Output (IPO)** (McGrath, 1964)
  - Helps understand team performance and how to optimize it.

- **Inputs**: Team composition, goals, and nature of the problem
- **Processes**: Within teams and -members
- **Outputs**: Aligned with task demands and team's goals and objectives

## What do Effective Teams Do?

- **Mental Models**: Shared understanding of goals, tasks, and roles
- **Transactive Memory**: Awareness of each member’s expertise (Patel et al., 2021; Ghamgosar et al., 2023)
- **Clear goals, participatory processes**: to build mutual understanding (Vogel et al., 2014)

## The Role of Communication {.smaller}

- **Foundation of Trust**: crucial for team effectiveness (Breuer et al., 2016; Bennett & Gadlin, 2014)
- **Building Trust**: 
    - Clear, open communication (Conn et al., 2019)
    - Culture of Dialogue: Deep listening and active engagement (O'Rourke et al., 2023)
    - Joint identification of goals (Roelofs et al., 2019)
    - Formal agreements (Forscher et al., 2023)
    - Joint social activities (boulder outing)

## Trust, Ctd.

- **Procedural Fairness**: 
    - Trust takes time, less feasible for ECR
    - Transparency can mitigate the need for trust (DeHart, 2017; Breuer et al., 2016; Zajac et al., 2021)
- **Codes of Conduct**: 
    - Establish behavioral norms, social safety, and fair crediting in team projects (Baumgartner et al., 2023).
    - Can be off-the-shelf: Contributor Covenant (Ehmke, 2014)
    - Or co-created, e.g.: [CORE Lab Philosophy](https://osf.io/preprints/psyarxiv/6jmhe)    


## When it Goes Wrong

- **Managing Conflicts**: 
    - Intellectual disagreements can advance knowledge if managed well (Collins, 1998)
        + Adversarial collaboration (Clark & Tetlock, 2023)
    - Use both preemptive strategies (CoC) and reactive approaches (problem-solving, empathy) (Marks et al., 2001)
- **Training and Development**: Train communication and conflict resolution skills (Read et al., 2016)

## Team Composition

**A Complex Affair**: 

- Impact on team effectiveness varies with task complexity, interdependence, and project duration (Carter et al., 2019)
- Alignment between expertise and team goals is essential, as are interpersonal factors (Twyman & Contractor, 2019)

## Team Composition and Diversity

Diversity is not a matter of equity, social justice, and good employership (Kamerlin, 2020)

Lack of diversity in recruitment, tenure, and promotion **costs** teams:

* Missing out on skilled candidated
* Missing essential perspectives and knowledge
* Alienating relevant stakeholders, reduced impact (Powell, 2018)

We need policy because natural tendency is to team up with "similar others" (Montoya and Horton 2013)

## Illustrating Lack of Diversity/Inclusivity

* On our "Nikolaustag", all employees receive a chocolate caricature  of an enslaved black person (Saint Nicholas' "helper")
* A colleague has a baby, but there are no pumping rooms available. Her office wall is made of glass
* A PhD student is sexually assaulted by their supervisor. No action is taken, and they now no longer feel comfortable coming to the supervisor for advice
* Another PhD student is told by full professor "I can see under your skirt when you walk down the stairs". HR starts a series of talks between the professor and PhD student, but it takes a mental toll

## Diversity conclusions

- People tend to prefer being around similar others 
- Diversity can improve team effectiveness (Liu et al. 2020)
- **Benefits**: fresh perspectives, innovation, creativity (Nielsen et al., 2017)
- **Challenges**: Can increase conflict, especially in geographically or culturally diverse teams (Polzer et al., 2006)
- Task-relevant diversity is essential

## What Makes a Good Team Member?

Driskell et al., 2006:

- Agreeableness: Best predictor of interpersonal success
    * Interested in people, sympathise with others, make people feel at ease
- Openness:Flexibility is virtually universally advantageous (Hackman & Morris, 1978)
    * Opposite: stubborn, views uncertainty as a threat, low tolerance for ambiguity
- Conscientiousness: Mixed findings
    * hardworking, prepared, organized, meet obligations thoroughly and on-time, be reliable

## Team Fluidity and Permeable Boundaries

> **Fluidity**: Teams can reconfigure as needed, adapting to changing task demands (O'Rourke et al., 2023; Mathieu et al., 2014)

- **Opportunities** (Tannenbaum et al. 2012; Zajac et
al. 2021):
    - Facilitates knowledge transfer
    - Brings fresh perspectives and ideas (Gruenfeld et al., 2000)
    - Enhances flexibility and adaptability (Gorman & Cooke, 2011).
- **Challenges**:
    - Overhead from onboarding
        * Establishing reproducibile workflows, CoC's etc facilitate this
    - Can weaken team cohesion and stability (Emich et al., 2022).
    - Shifts dynamics
    - ECRs: Risk of contributing without sufficient recognition (Craig, 2018)
        * Example: PhD's in physics completing without single publication
  

## Team Climate & Organizational Support

- **Team Climate**: Shaped by communication, team interactions, and a balance of individual and team needs (Getha-Taylor et al., 2014).
- **Institutional Support**: Innovation-friendly culture and structured support enhance collaboration (Crow & Dabars, 2019).
- **Psychological Safety**: Encourages risk-taking, trust, and cohesion, essential for achieving team goals (Edmondson, 1999).

## Motivational Factors
- **Interpersonal Relationships**: Linked to scientific productivity (DeHart, 2017; Love et al., 2023).
- **Team Efficacy**: Confidence and motivation among team members are critical for success.


## Team Size  
  
- **Team Sizes**:
  - Small teams (2-10 individuals): Agile, innovative, disruptive.
  - Large teams (hundreds or thousands): High-impact, coordinated efforts.
- **Balance**: A thriving research ecosystem requires both small and large teams (Wu, Wang, & Evans, 2019).
